esphome:
  name: energy_1
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password
