---
esphome:
  name: hallway
  platform: ESP8266
  board: d1_mini
#  arduino_version: dev
#  esphomelib_version: dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

# Enable logging
logger:
#  level: DEBUG

ota:
  password: !secret ota_password

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: false

sensor:
  - platform: bme280
    temperature:
      name: "Flur Temperatur"
      oversampling: 16x
      filters:
        - offset: -1.0
    pressure:
      name: "Flur Luftdruck"
    humidity:
      name: "Flur Luftfeuchtigkeit"
    address: 0x76
    update_interval: 15s

binary_sensor:
  - platform: gpio
    pin: GPIO16
    name: "Flur Bewegung"
    device_class: motion
  - platform: status
    name: "Flur Status"
