---
esphomeyaml:
  name: nfcreader
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:
  level: DEBUG

ota:
  password: !secret ota_password

i2c:
  sda: D2
  scl: D1
  scan: true

uart:
  rx_pin: GPIO3
  baud_rate: 9600

rdm6300:

# on_tag:
#   if:
#     condition:
#       lambda: |-
#         static std::string last_one = "";
#         if (x == last_one)
#           return false;
#         last_one = x;
#         return true;
#     then:
#       - do stuff with id

sensor:
  - platform: bme280
    temperature:
      name: "NFC Reader Temperatur"
      oversampling: 16x
    pressure:
      name: "NFC Reader Luftdruck"
    humidity:
      name: "NFC Reader Luftfeuchtigkeit"
    address: 0x76
    update_interval: 15s

font:
  - file: "Raleway-Light.ttf"
    id: font
    size: 20

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(font), "Hello World!");
