---
esphome:
  name: 'switch_1'
  platform: ESP8266
  board: esp01_1m
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

# Enable logging
logger:
#  level: DEBUG

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    name: "Teckin 1 Button"
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay

switch:
- platform: gpio
  id: blue_led
  pin:
    number: GPIO13
    inverted: True
- platform: gpio
  name: "Teckin 1 Relay"
  pin: GPIO14
  id: relay
  on_turn_on:
  - switch.turn_on: blue_led
  on_turn_off:
  - switch.turn_off: blue_led

# Use red LED for connectivity status indicator
status_led:
  pin:
    number: GPIO3
    inverted: True

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    # Higher value gives lower watt readout
    current_resistor: 0.00221
    # Lower value gives lower voltage readout
    voltage_divider: 871
    current:
      name: "Teckin 1 Current"
      accuracy_decimals: 2
    voltage:
      name: "Teckin 1 Voltage"
    power:
      name: "Teckin 1 Power"
    update_interval: 15s