---
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Magic Mirror'
    sensor.mm_display:
      icon: mdi:monitor
      friendly_name: Mirror Display
    switch.mm_display:
      icon: mdi:monitor
      friendly_name: Mirror Display
    script.mm_reboot:
      icon: mdi:lock-reset
    script.mm_shutdown:
      icon: mdi:power

sensor:
  - platform: command_line
    command: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no pi@192.168.178.50 \"[[ \\$(echo 'pow 0' | cec-client -s -d 1) =~ 'status: on' ]] && echo 'on' || echo 'off'\""
    name: mm display
    scan_interval: 30
# =======================================================================
#
# =======================================================================
switch:
  - platform: command_line
    switches:
      mm_display:
        value_template: "{{ is_state('sensor.mm_display', 'on') }}"
        command_on: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no pi@192.168.178.50 \"echo 'on 0' | cec-client -s -d 1\""
        command_off: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no pi@192.168.178.50 \"echo 'standby 0' | cec-client -s -d 1\""

# =======================================================================
#
# =======================================================================
shell_command:
  mm_reboot: "curl -s 'http://192.168.178.50:8080/remote?action=REBOOT'"
  mm_shutdown: "curl -s 'http://192.168.178.50:8080/remote?action=SHUTDOWN'"
# =======================================================================
#
# =======================================================================
script:
  mm_reboot:
    alias: Magic Mirror Reboot
    sequence:
      - data: {}
        service: shell_command.mm_reboot
  mm_shutdown:
    alias: Magic Mirror ShutDown
    sequence:
      - data: {}
        service: shell_command.mm_shutdown
