---
alexa:
  smart_home:
    filter:
      include_domains:
        - alarm_control_panel
        - fan
        - climate
        - cover
        - lock
      include_entities:
        - light.kuechenlicht
        - light.flurlicht
        - switch.kamera
        - switch.computer_zubehoer
        - light.bad_led
        - light.gateway_light_7811dcb9d0eb
        - light.kuche_led
        - light.tv_leds
        - light.leds_bei_den_pokalen
        - light.peg_board_leds
        - binary_sensor.door_window_sensor_158d0002046916
        - binary_sensor.door_window_sensor_158d00020b7d0f
        - binary_sensor.flur_bewegung
        - binary_sensor.klingel
        - binary_sensor.kuche_bewegung
        - binary_sensor.niklas_zimmer_bewegung
        - sensor.bad_luftfeuchtigkeit
        - sensor.bad_temperatur
        - sensor.flur_luftfeuchtigkeit
        - sensor.flur_temperatur
        - sensor.kuche_luftfeuchtigkeit
        - sensor.kuche_temperatur
        - sensor.niklas_zimmer_temperatur
        - switch.ritzdect_200_1
        - switch.mqttsign
        - switch.niklascomputer
        - light.bett_leds
        - switch.teckin_1_relay
        - switch.teckin_3_relay
        - light.desk_leds
automation:
  - action:
      - delay: 120
      - service: homekit.start
    alias: "Start HomeKit"
    initial_state: "on"
    trigger:
      - event: start
        platform: homeassistant
homekit:
  auto_start: false
  entity_config:
    switch.ritzdect_200_1:
      type: outlet
  filter:
    include_domains:
      - alarm_control_panel
      - fan
      - climate
      - cover
      - lock
    include_entities:
      - light.kuechenlicht
      - light.flurlicht
      - switch.kamera
      - switch.computer_zubehoer
      - light.bad_led
      - light.gateway_light_7811dcb9d0eb
      - light.kuche_led
      - light.tv_leds
      - light.leds_bei_den_pokalen
      - light.peg_board_leds
      - binary_sensor.door_window_sensor_158d0002046916
      - binary_sensor.door_window_sensor_158d00020b7d0f
      - binary_sensor.flur_bewegung
      - binary_sensor.klingel
      - binary_sensor.kuche_bewegung
      - binary_sensor.niklas_zimmer_bewegung
      - sensor.bad_luftfeuchtigkeit
      - sensor.bad_temperatur
      - sensor.flur_luftfeuchtigkeit
      - sensor.flur_temperatur
      - sensor.kuche_luftfeuchtigkeit
      - sensor.kuche_temperatur
      - sensor.niklas_zimmer_temperatur
      - switch.ritzdect_200_1
      - switch.mqttsign
      - switch.niklascomputer
      - light.bett_leds
      - switch.teckin_1_relay
      - switch.teckin_3_relay
      - light.desk_leds
  name: !secret host_name
notify:
  - command: "/config/alexa_wrapper.sh -d \"Niklas' Echo\""
    name: "Niklas' Echo"
    platform: command_line
  - command: "/config/alexa_wrapper.sh -d \"Niklas's Sonos One\""
    name: "Sonos One"
    platform: command_line

google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include ../google_assistant_service_account.json
  report_state: true
  exposed_domains:
    - alarm_control_panel
    - fan
    - climate
    - cover
    - lock
  entity_config:
    light.kuechenlicht:
      expose: true
    light.flurlicht:
      expose: true
    switch.kamera:
      expose: true
    switch.computer_zubehoer:
      expose: true
    light.bad_led:
      expose: true
    light.gateway_light_7811dcb9d0eb:
      expose: true
    light.kuche_led:
      expose: true
    light.tv_leds:
      expose: true
    light.leds_bei_den_pokalen:
      expose: true
    light.peg_board_leds:
      expose: true
    binary_sensor.door_window_sensor_158d0002046916:
      expose: true
    binary_sensor.door_window_sensor_158d00020b7d0f:
      expose: true
    binary_sensor.flur_bewegung:
      expose: true
    binary_sensor.klingel:
      expose: true
    binary_sensor.kuche_bewegung:
      expose: true
    binary_sensor.niklas_zimmer_bewegung:
      expose: true
    sensor.bad_luftfeuchtigkeit:
      expose: true
    sensor.bad_temperatur:
      expose: true
    sensor.flur_luftfeuchtigkeit:
      expose: true
    sensor.flur_temperatur:
      expose: true
    sensor.kuche_luftfeuchtigkeit:
      expose: true
    sensor.kuche_temperatur:
      expose: true
    sensor.niklas_zimmer_temperatur:
      expose: true
    switch.ritzdect_200_1:
      expose: true
    switch.mqttsign:
      expose: true
    switch.niklascomputer:
      expose: true
    light.bett_leds:
      expose: true
    switch.teckin_1_relay:
      expose: true
    switch.teckin_3_relay:
      expose: true
    light.desk_leds:
      expose: true
